[package]
name = "embedded-graphics-profont"
version = "0.3.0"
edition = "2024"
authors = ["TESSON-MAKER"]
description = "Bitmap font rendering for embedded-graphics with anchor and tracking support"
readme = "README.md"
repository = "https://github.com/TESSON-MAKER/embedded-graphics-profont"
license = "MIT"

[dependencies]
embedded-graphics = "0.8.2"